version: '3.7'

services:
    instanceid-api-news:
        build: news-api/
        container_name: instanceid-api-news
        entrypoint: entrypoint.sh
        ports:
            - "9004:9004"
        restart: always
        networks:
            - instanceid-api
        volumes:
            - ./.certs/:/certs/
            - ./news-api/:/news-api/

networks:
    instanceid-api:
      driver: bridge
      name: instanceid-api-net